### ISSUE TITLE
panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by miskryt** [gnanderson/rbh#9]
user@DS4298:~/rippled/build$ ./rbh run
2019/08/05 15:16:00 firewall: zone -  internal
2019/08/05 15:16:00 Dial: connection was successfully established with ws://127.0.0.1:6006
panic: non-positive interval for NewTicker

goroutine 38 [running]:
time.NewTicker(0x0, 0xc0001a6178)
        /usr/local/go/src/time/tick.go:23 +0x147
github.com/gnanderson/xrpl.(*Node).RepeatCommand.func2(0x0, 0xa388a0, 0xc0000aaac0, 0xc0001a8000, 0xa2e460, 0xc00000e0e8)
        /home/graham/pkg/mod/github.com/gnanderson/xrpl@v0.0.9/commands.go:82 +0x4a
created by github.com/gnanderson/xrpl.(*Node).RepeatCommand
        /home/graham/pkg/mod/github.com/gnanderson/xrpl@v0.0.9/commands.go:81 +0xf1

What does it means?

**Comment by gnanderson** [comment]
Thanks for reporting this @tropa 

The error originates from the standard library's [`time` package](https://golang.org/src/time/tick.go).

I suspect you have some time drift or some sudden time slew on the system. Are you running `rippled` and `rbh` in a virtualised environment? If so, maybe check if ntp is keeping your system time accurate. Often it can drift if the physical host is under resource pressure and perhaps not also kept in good time sync.

If you think there may be another reason, please re-open this issue, thanks!

Graham

**Comment by gnanderson** [comment]
Thanks for reporting this @tropa - In my haste I just closed this thinking it would be time drift on the system (if it was virtualised).

However, having read the standard library package where the error originates I'll poke further, could be bug in my handling of the default flag value for the repeating check.
